kettle17/group-project-bandcamp

- .gitignore
- pipeline/extract.py
- pipeline/load.py
- pipeline/test_extract.py
- pipeline/test_load.py
- pipeline/test_transform.py
- pipeline/transform.py
- requirements.txt
Created the general file structure for the project. 
As a developer, I want to have my files sorted out neatly in an introduction template, so I can code easier.
Helps sort out all files ahead of time so that work can be started on the scripts.
Also allows CI/CD to run.
Developers.
The checking of commits.
When a developer pushes code onto the repo.
On Github
Implement the github actions on the the local code folder instead of on the github actions tab.
Should run pytest and pylint on every push.
> Created general file structure + github actions fix. 

- pipeline/test_extract.py
- pipeline/utilities.py
- requirements.txt
Setting up a good example test and preparing for ETL pipeline.
Making sure that I don't leave an awful test in the code.
1/1 pytest.
> Fix example test and add utilities file.

- README.md
- pipeline/README.md
- terraform/README.md
This PR adds READMEs to each subdirectory and fleshes out the root directory's README.
Non-root READMEs structures have been started but not finished so we can write more about the architecture when we have it up and running.
We need this documentation for readability.
N/A
> Create general READMEs for each subdirectory in project.

- pipeline/README.md
- pipeline/load.py
This PR adds function signatures and docstrings for the `load.py` script for the ETL pipeline.
This establishes the load portion of the ETL pipeline development. Following a TDD approach - first creating function signatures and checking them, then writing tests before finally implementing the functions to ensure they pass the tests.
Not yet tested - this PR contains only function signatures. Tests will be added in the next PR following TDD methodology.
> Add load.py function signatures (TDD).

- pipeline/schema.sql
Wrote a schema.sql file containing all SQL commands to create the tables and relationships for the tracktion database.
This is required to create the tables and relationships for the database.
Created and connected to a local database and tested running the schema file a few times.
> Schema for tracktion database.

- pipeline/test_transform.py
- pipeline/transform.py
This PR adds function signatures and docstrings for the `transform.py` script for the ETL pipeline.
This establishes the transform portion of the ETL pipeline development. Following a TDD approach - first creating function signatures and checking them, then writing tests before finally implementing the functions to ensure they pass the tests.
Not yet tested - this PR contains only function signatures. Tests will be added in the next PR following TDD methodology.
> Updates to transform function signatures (TDD).

- pipeline/load.py
- pipeline/test_load.py
This PR:
- Implements tests for `test_load.py`.
- Skips the test file whilst `load.py` functions aren't implemented (TDD - RAG)
We would like a good amount of tests prior to us implementing functions, this follows TDD principles and reduces the likelihood of bugs later in development.
Pytest ran, all tests pass.
> Implement test functions for load.

- terraform/README.md
- terraform/main.tf
- terraform/variables.tf
This PR:
- Adds initial Terraform configuration for provisioning an RDS PostgreSQL instance.
- Creates supporting resources: DB subnet group and security group.
- Updates README.md with setup instructions and file structure.
Sets up the foundational infrastructure required for running the ETL pipeline on AWS.
- Applied the Terraform configuration using terraform apply with tfvars.
- Connected to the RDS instance via psql to verify the database is accessible.
- Ran the schema.sql file in the codebase to create required tables.
> [PR] Create RDS database using terraform.

- pipeline/schema.sql
added merchandise_name column to merchandise table, removed NOT NULL constraints on art_url column, changed album_name and track_name types to TEXT instead of VARCHAR(50).
As a developer, I want to have an accurate schema so that I can insert the relevant data into the database.
There were some gaps in the schema (missing merchandise name column) and not null constraints on columns that will sometimes have null values due to not every item having an art_url. Therefore the schema needed editing to address these gaps.
A change to the schema, ran the schema file in a local database to test it.
> [PR] Change column types and add merchandise name column

- pipeline/extract.py
- pipeline/test_extract.py
Fixed URL bug in extract.py
Fixes #97 
Pytest suite. Fixed 1 test that relied on url output
> [PR] Fix URL bug in extract.py

- pipeline/Dockerfile
- pipeline/README.md
- pipeline/etl_controller.py
- pipeline/requirements.txt
Created a Dockerfile for containerising the ETL pipeline, also implemented the lambda handler to facilitate this.
We need a dockerised image of our ETL pipeline in order to run it scheduled in the cloud.
Built the Docker file locally using `docker build` ran it and queried it using a `curl` command.
> Add Dockerfile and ETL lambda handler

- streamlit/pages/Privacy_Policy.py
Created a simple Privacy Policy page that aims to cover GDPR
As a secret agent, I want to sign up to the dashboard with the confidence that I can request for my data to be removed later, so I can keep my identity under wraps.
GDPR compliancy, helps if we want to promote our product later with the intention if it being sold later
> [PR] Created simple privacy policy page.

- alerts/queries.sql
- pipeline/README.md
- streamlit/README.md
- terraform/README.md
Most README.md updated excluding the directories that are currently being worked on.
Important for developers to have documentation on how this project works.
Opened the preview for each README and ensured it aligned with the repo.
> [PR] Update all of the readme.md files across entire repo.

- alerts/Dockerfile
- alerts/alerts.py
- alerts/queries.sql
- alerts/requirements.txt
This PR connects to the database and retrieves artist and revenue data and then analyses it using pandas to get trending artists which are classified as those 
As a music listener, I want to receive alerts about rising artists/genres so that I can discover new music and talent.
To address the issue that rising talent is only discovered after they've gained popularity, we want to create an alert system that can spot upcoming artists/genres and send alerts to subscribers.
The documentation will be updated under a different issue.
> [PR] Alert script that gets trending artists

- sales_report/README.md
This pr includes the read me for the report script.
As a developer I want to read the readme for a folder so that I can understand the project if I wish to replicate it
Need to have a clear read me so that other developers can understand the structure/purpose of the directory
> [PR] Write read me for report directory.

- streamlit/pages/Alerts.py
Added a new menu to the alerts page and added the option for users to unsubscribe
As a record manager, I want to receive trending artist alerts so I know what rising talent I can sign
Allows bridge to another functionality
> [PR] Added new menu to alerts page + added option for users to unsub

- README.md
Add two lines to the root README with missing environment variables.
> [PR] Update root README.md

- sales_report/README.md
Bullet pointed report readme
As a user I want to know more about the system so i can feel empowered
Helps readability of repo and updates documentation
Deletes unused files with clutter up the repo
> [PR] Small formatting changes to report README

- pipeline/load.py
- pipeline/schema.sql
Fixed warning from pytest.
Changed schema to account for smallint->bigint bug which we fixed.
As a user, I want to feel confident that the program I'm using is bug free, so I can feel safe with using it.
Gets rid of warning
Fixed schema
79/79 no warnings
> [PR] 1 warning from test + schema fix

- alerts/README.md
This pr includes the read me for the alerts script.
As a developer I want to read the readme for a folder so that I can understand the project if I wish to replicate it
Need to have a clear read me so that other developers can understand the structure/purpose of the directory
> [PR] Read me for alerts directory.
